(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;const $=(s,r=document)=>[...r.querySelectorAll(s)];const loader=document.querySelector('.loader');addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),reduce?80:900),{once:true});
const nav=document.getElementById('nav'),bar=document.querySelector('.progress i'),links=$('.nav-links a'),sections=$('main section[id]');function update(){const y=scrollY,max=Math.max(1,document.documentElement.scrollHeight-innerHeight);if(nav)nav.classList.toggle('scrolled',y>35);if(bar)bar.style.transform='scaleX('+Math.min(1,y/max)+')';let current='home';sections.forEach(s=>{if(s.getBoundingClientRect().top<=innerHeight*.42)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))}addEventListener('scroll',update,{passive:true});update();
const menu=document.querySelector('.menu'),navLinks=document.querySelector('.nav-links');menu?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const reveal=$('.reveal');if('IntersectionObserver'in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -7% 0px'});reveal.forEach(x=>io.observe(x))}else reveal.forEach(x=>x.classList.add('visible'));
if(fine&&!reduce){const cursor=document.querySelector('.cursor');let cx=-50,cy=-50,tx=-50,ty=-50;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY});const cursorLoop=()=>{cx+=(tx-cx)*.16;cy+=(ty-cy)*.16;if(cursor){cursor.style.left=cx+'px';cursor.style.top=cy+'px'}requestAnimationFrame(cursorLoop)};requestAnimationFrame(cursorLoop);$('a,button,.tech,.facts>div').forEach(el=>{el.addEventListener('mouseenter',()=>cursor?.classList.add('hover'));el.addEventListener('mouseleave',()=>cursor?.classList.remove('hover'))});
const portrait=document.querySelector('.portrait-frame');portrait?.addEventListener('pointermove',e=>{const r=portrait.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;portrait.style.transform='translateX(-50%) rotateX('+(-y*4).toFixed(2)+'deg) rotateY('+(x*6).toFixed(2)+'deg) rotate(0deg) scale(1.01)'});portrait?.addEventListener('pointerleave',()=>portrait.style.removeProperty('transform'));
$('.project-media,.project-thumb').forEach(card=>{const img=card.querySelector('img');card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;if(img)img.style.transform='scale(1.055) translate('+(-x*6).toFixed(1)+'px,'+(-y*4).toFixed(1)+'px)'});card.addEventListener('pointerleave',()=>img?.style.removeProperty('transform'))});
}
if(!reduce){const wheel=document.querySelector('.tech-wheel');let t=0;const loop=()=>{t+=.004;if(wheel&&fine)wheel.style.transform='rotate('+Math.sin(t)*1.2+'deg)';requestAnimationFrame(loop)};requestAnimationFrame(loop)}
})();